ACM: Init acm

diff --git a/dist/autossl b/dist/autossl
--- a/dist/autossl
+++ b/dist/autossl
@@ -131,8 +131,23 @@ sync-cert () {
     elif [ "$1" = "" ]; then
         echo "Please specify provider to sync"
     elif [ "$1" = "iam" ]; then
-        echo "Syncing certificates to AWS IAM"
+        echo "Importing certificates to AWS IAM, please don't cancel during this operation"
+        
+        if ! has-command aws; then
+            install-aws
+        fi
+
         iam-sync-cert
+    elif [ "$1" = "acm" ]; then
+        echo "Importing certificates to AWS ACM, please don't cancel during this operation"
+
+        if ! has-command aws; then
+            install-aws
+        fi
+        
+        acm-sync-cert
+    else
+        echo "[ERROR] Not supported cloud provider: $1"
     fi
 }
 install-aws () {
@@ -156,20 +171,14 @@ iam-sync-cert () {
     DATE=`date '+%Y-%m'`
     SITES=$(list-certs)
 
-    if ! has-command aws; then
-        install-aws
-    fi
-
     if [ "$SITES" == "" ]; then
         return
     fi
 
-    echo "Uploading certificates to IAM, please don't cancel during this operation"
-
     for SITE_NAME in $SITES 
     do
         CERT_NAME="$(get-cert-name $SITE_NAME)-$DATE"
-        echo "Uploading certificates for site: $SITE_NAME  -->  $CERT_NAME"
+        echo "Importing certificates for site: $SITE_NAME  -->  $CERT_NAME"
         missing_certfile=0
 
         for cert_file in $FILE_LIST;
@@ -198,8 +207,81 @@ iam-sync-cert () {
             --certificate-body "file:///$LOCAL_PATH/$SITE_NAME/cert.pem" \
             --private-key "file:///$LOCAL_PATH/$SITE_NAME/privkey.pem" \
             --certificate-chain "file:///$LOCAL_PATH/$SITE_NAME/chain.pem" 1>/dev/null; then
-            echo "Done"
+            echo "Created"
         fi
+    done
+}
+acm-sync-cert () {
+    FILE_LIST="cert.pem privkey.pem chain.pem"
+    SITES=$(list-certs)
+
+    if [ "$SITES" == "" ]; then
+        return
+    fi
+
+    ACM_ARNS_STR=$(acm-list-cert-arns)
+    declare -a ACM_ARNS=($ACM_ARNS_STR)
+    declare -a ACM_NAMES=($(acm-list-cert-names "$ACM_ARNS_STR"))
+
+    for SITE_NAME in $SITES 
+    do
+        CERT_NAME="$(get-cert-name $SITE_NAME)"
+        echo "Importing certificates for site: $SITE_NAME  -->  $CERT_NAME"
+        missing_certfile=0
+
+        for cert_file in $FILE_LIST;
+        do
+            file_path="$LOCAL_PATH/$SITE_NAME/$cert_file"
+
+            if [ ! -f $file_path ]; then
+                echo " - Missing $cert_file"
+                missing_certfile=1
+            fi
+        done
+
+        if [ missing_certfile = 1 ]; then
+            echo "[ERROR] Missing certificate file for $SITE_NAME"
+            continue
+        fi
+
+        if [ "$CERT_NAME" = "" ]; then
+            echo "[ERROR] Can't get cert name for $SITE_NAME"
+            continue
+        fi
+
+        acm_arn=""
+        for i in "${!ACM_NAMES[@]}"; do
+            if [ "${ACM_NAMES[$i]}" = "$CERT_NAME" ]; then
+                acm_arn="${ACM_ARNS[$i]}"
+            fi
+        done
+
+        if [ "$acm_arn" = "" ]; then
+            if aws acm import-certificate \
+                --certificate "file:///$LOCAL_PATH/$SITE_NAME/cert.pem" \
+                --private-key "file:///$LOCAL_PATH/$SITE_NAME/privkey.pem" \
+                --certificate-chain "file:///$LOCAL_PATH/$SITE_NAME/chain.pem" 1>/dev/null; then
+                echo "Created"
+            fi
+        else
+            if aws acm import-certificate \
+                --certificate-arn "$acm_arn" \
+                --certificate "file:///$LOCAL_PATH/$SITE_NAME/cert.pem" \
+                --private-key "file:///$LOCAL_PATH/$SITE_NAME/privkey.pem" \
+                --certificate-chain "file:///$LOCAL_PATH/$SITE_NAME/chain.pem" 1>/dev/null; then
+                echo "Updated"
+            fi
+        fi
+    done
+}
+acm-list-cert-arns () {
+    echo "$(aws acm list-certificates --query 'CertificateSummaryList[*].CertificateArn' --output text)"
+}
+acm-list-cert-names () {
+    declare -a ACM_CERTIFICATES=$1
+
+    for cert_arn in $ACM_CERTIFICATES; do
+        aws acm describe-certificate --certificate-arn "$cert_arn" --query "Certificate.SubjectAlternativeNames | sort(@)" --output text | sed -E 's:\s+:-:g' | sed -e "s:*:+:g"
     done
 }
 MODE="$1"
